namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP 
  type: ClusterIP 
 
image:
  repository: toanla1306/techtrends
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

resources:
  request:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

livenessProbe:
    httpGet:
      path: /healthz
      port: 3111
readinessProbe:
    httpGet:
      path: /healthz
      port: 3111